
service: aws-serverless-lambda
app: try-it-on
provider:
  name: aws
  runtime: nodejs12.x
functions:
  index:
    handler: src/app.handler
    events:
     - http:
         path: /hello_world
         method: get
     - http:
         path: /users/{id}
         method: get
     - http:
         path: /users
         method: get
     - http:
         path: /users
         method: post
     - http:
         path: /users/{id}
         method: put
     - http:
         path: /users/login
         method: post
     - http:
         path: /users/logout 
         method: post

